### ISSUE TITLE
being able to load html from a file ?

### ISSUE THREAD

**Issue by maboiteaspam** [jonathantneal/mdcss#1]
Hi!

how do you think about importing html template via a specific instruction instead of inline it within the html comment ?

I feel little bothered to put indented html in the css comments, for some more complex components.

thanks ! Great software ! looks really cool.

**Comment by jonathantneal** [comment]
That’s a really great idea. I wonder if it may work best to add a special `import` meta property to handle this.

**Comment by grouchal** [comment]
What would be great would be the support to load external handlebars files for the HTML this enables and HTML to be reused in the style guide to and the actual system.

**Comment by jonathantneal** [comment]
Feel free to open a separate issue for handlebars, because I would need more details into how that would work and how data might be passed into the template. However, this feature has since been added to mdcss: https://github.com/jonathantneal/mdcss#writing-documentation

**Comment by entioentio** [comment]
Hi @jonathantneal,
I'm just using this awesome import option, but constantly hitting the wall.
It seems that imported .md files aren't processed by mdss. They're just being imported and printed as plain string.
Can You post maybe some tip or suggestion on what am i doing wrong? Or maybe some workaround?

My test setup is as follows;
css file:

```
/*---
title:   buttons
section: Typography
import: _buttons.md
---*/
```

buttons.md:

``````
Button styles can be applied to **any** element. Typically you'll want to use
either a `<button>` or an `<a>` element:

```example:html
<button class="btn">Click</button>
<a class="btn" href="/some-page">Some Page</a>
```
``````

Thanks in advance!
