### ISSUE TITLE
Section order in left nav (question)

### ISSUE THREAD

**Issue by asifshirazi** [jonathantneal/mdcss#10]
Is there any way to re-order any section in side bar nav?

**Comment by jonathantneal** [comment]
There is not a convenience method that can be used from the markdown at this time. It is in order of appearance. How might you want this feature to work? Like so?

``` css
/*---
title:   Subheadings
section: Base CSS
order: -1
---
```

This example would push `Subheadings` to the top.

**Comment by asifshirazi** [comment]
yes....! this is what I need to say :) this enhancement will be helpful for us.

**Comment by jonathantneal** [comment]
Great, I will look into adding this.

**Comment by asifshirazi** [comment]
Thats cool!, thank you so much @jonathantneal

**Comment by jonathantneal** [comment]
Great suggestion, again. This is now available in mdcss-theme-github [v2.2.0](https://github.com/jonathantneal/mdcss-theme-github/commit/9d92dab27343967f253d3f924260a573c13706a2)

Use `order: <number>` to sort anything.

**Comment by TxHawks** [comment]
This isn't anywhere in the documentation, right? I couldn't find any mention of it.

**Comment by jonathantneal** [comment]
If there is not, I would welcome a pull with the documentation. Otherwise, we rely on my remembering to write it, or writing another issue to remind me to do it. :)

**Comment by TxHawks** [comment]
Is there a way to control the order of the sections themselves rather than that of the subsections?

I mean, push the `Base CSS` section to the top instead of pushing `subheadings` to the top of `Base CSS`.
