### ISSUE TITLE
Front Matter and Nav Missing

### ISSUE THREAD

**Issue by stephenway** [jonathantneal/mdcss#11]
Just upgraded to 1.4.0 and my front matter and nav are missing. I paired it down to 2 partials as well and it won't work for some reason.
![screen shot 2016-01-28 at 2 19 37 pm](https://cloud.githubusercontent.com/assets/38894/12660840/d4d177a6-c5ca-11e5-8742-7d13ec03e098.png)

In my processors:

``` js
require('mdcss')({
       theme: require('mdcss-theme-github')({
               js: ['dom.js'],
               css: ['style.css', 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400italic,600,700',
 'https://fonts.googleapis.com/icon?family=Material+Icons'],
               examples: ({
                       htmlcss: '',
                       bodycss: 'margin:1em;',
                       css: ['style.css', 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400italic,6
00,700', 'https://fonts.googleapis.com/icon?family=Material+Icons']
               })
       })
}),
```

My front matter is formatted like this:

``` js
/*---
 title: Grid
 section: Utilities
 ---

 Docs...

*/
```

If this is more related to how the github theme works, then I can move this issue to that repo? Thanks

**Comment by jonathantneal** [comment]
I’m so sorry to hear about this. This project is fairly near to my heart, so I’ll see if I can look into it tonight. I have a pretty full plate, but I don’t want anyone to feel turned away by mdcss.

**Comment by stephenway** [comment]
Thanks @jonathantneal I understand and respect your time.

**Comment by jonathantneal** [comment]
Thanks for your patience. I was able to fix the problem and I’ve published the update!

**Comment by stephenway** [comment]
Awesome, thanks for the quick turn-around! :+1:

**Comment by jonathantneal** [comment]
Would you confirm that it’s working for you so that we might close this?

**Comment by stephenway** [comment]
Confirmed!
