### ISSUE TITLE
Permission Error.

### ISSUE THREAD

**Issue by ethyde** [jonathantneal/mdcss#17]
As I said in #12, with version 1.5.1, when I start the task, it create the `styleguide` folder, and fail after with the following error : 
![permission error](https://cloud.githubusercontent.com/assets/409987/12952048/6942c8c8-d015-11e5-99b3-e60e10d18225.jpg)

**Comment by stephenway** [comment]
@ethyde  Could you share your build file (like gulp webpack) so I can try to replicate your issue? Closing for now because we have a new patch release out that potentially fixes this.
