### ISSUE TITLE
[crlf] is not recognized

### ISSUE THREAD

**Issue by maboiteaspam** [jonathantneal/mdcss#2]
Hi,

noticed that when a document use CRLF instead of LF, the parser won t recognize the comments.

problem lies here
https://github.com/jonathantneal/mdcss/blob/master/index.js#L37

and 

https://github.com/jonathantneal/mdcss/blob/master/index.js#L5

I d suggest to to improve the `README` to invite windows user to stack a task to convert the new lines.

Much like you did for postcss.

That way the regexp can stay simple.

**Comment by jonathantneal** [comment]
Alternatively, I could use `[\n\r]+`, yes?

**Comment by maboiteaspam** [comment]
Hi,

How about using `m` modifier ? With a slight change in the regex, like this

``` js
var isDoc  = /^\s*-{3,}\s(?:([\W\w]*?)\s\s*-{3,})?/m;
var isMeta = /([A-z][\w-]*)\s*:\s*([\w-][^\s]*)/g;
```

on my copy here, i made the change, re generated, then it worked.

But i did not run the test.

for reference,
http://stackoverflow.com/questions/918806/difference-between-regular-expression-modifiers-m-and-s
http://stackoverflow.com/questions/1979884/how-to-use-javascript-regex-over-multiple-lines
