### ISSUE TITLE
option to include all images in a folder

### ISSUE THREAD

**Issue by TxHawks** [jonathantneal/mdcss#20]
It would be really great if it is was possible to include all images located in a specified directory.

This could be used, for example, to automate the documenting of of svg icons, which I think is crucial for a styleguide.

I would think that is should include the image and the file name (and if the svg tag has an ID attribute, than that as well, which would be really useful when using inline svg sprites).

**Comment by stephenway** [comment]
This seems like it could be a new example type in your theme. Check out `color` in examples.js of your theme. You can easily make your own that iterates over each icon you specify.

**Comment by stephenway** [comment]
You can now specify `assets` option to include your image folder from your project like `mdcss({ assets: ['img', 'fonts', 'js'] })`
