### ISSUE TITLE
Request: ability to specify path for import detail

### ISSUE THREAD

**Issue by TxHawks** [jonathantneal/mdcss#24]
Right now, it seems like mdcss only knows to look for files imported using the `import` detail in the same
directory as the CSS file.

I think one common use-case for `import` is for importing the README file at the beginning of your styleguide.

If I have the following file structure:

```
_  ./
|__ css/
|__ README.md
```

Trying to import the `README.md` with

``` css
/* ---
title: Intro
import: ../README.md
--- */
```

Produces the following HTML

``` html
<section id="intro">
  <h2>Intro</h2>
  <div>
    <h2 id="import-readme-md">import: ../README.md</h2>
  </div>
</section>
```

**Comment by tbekaert** [comment]
I think you forgot something in your `README.md`.

```
/* ---
title: Intro
import: ../README.md
--- */
```

Does this works?

**Comment by TxHawks** [comment]
It was just a typo when submitting the reduced test case, real css file does have a `:` after import, and no, unfortunately, it does not work.

**Comment by hiulit** [comment]
I found a solution for this.
At the top of the `index.js'  there are a couple of regexs.

Here's how I left mine so they work with relative paths:

```
var isDoc = /^\s*-{3,}\n((?:[ \t]*[A-z][\w-]*[ \t]*:[ \t]*[\w\-\.\/][^\n]*\n*)*)(?:[ \t]*-{3,})?/;
var isMeta = /([A-z][\w-]*)[ \t]*:[ \t]*([\w\-\.\/][^\n]*)/g;
```

I've got something like this:

```
/*---
title:   Buttons
import: ../../md/buttons.md
---*/
```

I don't know if it's the optimal way to go, but it works for me :)

**Comment by stephenway** [comment]
@hiulit Looks like a simple PR :+1:
