### ISSUE TITLE
idoc.body is null

### ISSUE THREAD

**Issue by tbekaert** [jonathantneal/mdcss#25]
Hi,

I have a small issue using mdcss. I generate my styleguide using Gulp, like so:

```
require('mdcss')({
  assets: [
    path.css + "app.css",
    path.js + "app.min.js"
  ],
  examples: {
    css: ['app.css'],
    js: ['app.min.js']
  }
})
```

It copy my files in the styleguide folder and files to include are well linked in the html:

```
<script>examples={"base":"","target":"_self","css":["app.css"],"js":["app.min.js"],"bodyjs":[],"htmlcss":"background:none;border:0;clip:auto;display:block;height:auto;margin:0;padding:0;position:static;width:auto","bodycss":"background:none;border:0;clip:auto;display:block;height:auto;margin:0;padding:16px;position:static;width:auto"};</script>
```

Unfortunately, when I load the `index.html` file in my browser, I get the following error and my style and script files are not loaded:

```
Uncaught TypeError: Cannot read property 'setAttribute' of null (examples.js:114)
```

It seems like `idoc.body` is `null` but I don't understand why. Commenting this line though seems to remove the issue but I would like to have a better solution for this. Do you have any clue on why this is happening?

**Comment by tbekaert** [comment]
I've just notice it was a bug in Github Theme so I've created a PR to fix that

**Comment by stephenway** [comment]
This issue can be closed.
