### ISSUE TITLE
The style guide does not catch my styles

### ISSUE THREAD

**Issue by gabrielmanara** [jonathantneal/mdcss#33]
Hey @jonathantneal, my CSS don't compile with the Styleguide.

Here is my gulp task:

```
'use strict';
var postcss = require('gulp-postcss');

module.exports = function (gulp, $, config) {
  return function() {
    gulp.src('./dist/css/style.css').pipe(
      postcss([
        require('mdcss')({
          examples: {
            css: ['../dist/css/style.css']
          }
        })
      ])
    )
  };
};
```

Can you help me?

**Comment by mtinner** [comment]
This will may help you
https://github.com/mtinner/CAS-FEE_Project2/blob/develop/src/main/frontend/gulp/styleguide.js

and make sure you have set your line separator to lf

**Comment by gabrielmanara** [comment]
Thanks @mtinner. Now it's work!
