### ISSUE TITLE
documented css should also be processed in the style guides document

### ISSUE THREAD

**Issue by maboiteaspam** [jonathantneal/mdcss#4]
Hi,

I have this css documentation

``````
    /*---
    title:   f-brand + f-light
    section: Text
    ---

    Lowercase text:

    <div class='f-brand f-light'>lorem ipsum</div>

    ```html
    <div class='f-brand f-light'>lorem ipsum</div>
    ```
    */
    .f-brand .f-light,
    .f-brand.f-light{
        font-weight: normal;
        font-family: FuturaStdLight, Arial;
    }
``````

Which is working smoothly : )

Except that i would really like to also display the resulting rendering, which is why i have twice the same HTML block. One within a code block to show the markup, one outside of the code block to generate the rendering.

Problem is my documented css are not imported within the context of the document page.

I see in the readme, the first example include a demo of the button after the render, i d like to do the same thing.

Did i miss something ?

**Comment by jonathantneal** [comment]
This sounds like a case for `example:html`.

`````` css
/*---
title:   f-brand + f-light
section: Text
---

Lowercase text:

​```example:html
<div class='f-brand f-light'>lorem ipsum</div>
​```
*/
``````

Would that be what you wanted?

**Comment by maboiteaspam** [comment]
Hi,

no, that won t work,

see
![image](https://cloud.githubusercontent.com/assets/530732/11265059/fea1a430-8ed3-11e5-85b5-61198ba508cd.png)

with this doc,

``````
/*---
title:   f-brand + f-light
section: Text
---

Lowercase text:

```example:html
<div class='f-brand f-light'>lorem ipsum</div>
```

```html
<div class='f-brand f-light'>lorem ipsum</div>
```
*/
.f-brand .f-light,
.f-brand.f-light{
    font-weight: bold;
    font-family: FuturaStdLight, Arial;
}
``````

BTW, as you can see the invisible character is not needed , just prefix the markdown with 4 spaces.
(becaue I copy - pasted your suggestions, and that broke ; ) again )

**Comment by maboiteaspam** [comment]
hi,

i have dig a little more about that.

So somehow, i have been able to inject my css files into the iframe.

Except that one the css defines fonts-family and they are not reachable from mdcss resulting file.

So, my guess is that it can t be about copying only the parsed css file, but instead provide a whole directory to copy into styleguide folder.
Then it may work.

Any suggestions ? Seems like you already prepared some work around that (iframe isolation)

**Comment by maboiteaspam** [comment]
for reference, it more or less looks likes this

``` patch
Index: node_modules/mdcss/index.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- node_modules/mdcss/index.js (revision )
+++ node_modules/mdcss/index.js (revision )
@@ -112,6 +112,7 @@
        // return theme executed with parsed list, destination
        return opts.theme({
            list: list,
+           file: css.source.input.file,
            opts: opts
        }).then(function (docs) {
            return Promise.all([
```

``` patch
Index: node_modules/mdcss/node_modules/mdcss-theme-github/index.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- node_modules/mdcss/node_modules/mdcss-theme-github/index.js (revision )
+++ node_modules/mdcss/node_modules/mdcss-theme-github/index.js (revision )
@@ -32,9 +32,9 @@
        docs.template = path.join(__dirname, 'template.ejs');

      fs.writeFileSync(
+       path.join(__dirname, 'assets', path.basename(docs.file)),
+       fs.readFileSync(docs.file)
      )

        // set theme options
        docs.themeopts = themeopts;
@@ -49,7 +49,7 @@
                    // set examples options
                    docs.opts = ext({}, docs.opts, docs.themeopts);

+                 docs.opts.examples.css.push(""+path.basename(docs.file))

                    // set compiled template
                    docs.template = ejs.compile(contents)(docs);
```

**Comment by plesiecki** [comment]
Hello @maboiteaspam. Try following configuration 

``` javascript
require('mdcss')({
    theme: require('mdcss-theme-github')({
        examples: {
            css: ['style.css', '../build/main.css']
        }
    })
}),
```

Also this doc http://jonathantneal.github.io/mdcss-theme-github/demo/#options might be helpful

**Comment by jonathantneal** [comment]
Thanks @plesiecki. Closing this one out.

**Comment by tommilimmot** [comment]
@jonathantneal,
Mdcss is already parsing the comments in the css file. Couldn't it parse the style declarations as well and add/reference them in the iframe for an example:html? (Is there a specific reason why the parsed css file has to be added separately to the examples.css map?)
