### ISSUE TITLE
Error: EEXIST: file already exists

### ISSUE THREAD

**Issue by jonathanasquier** [jonathantneal/mdcss#40]
Hi, I'm having this error using mdcss as unique postcss plugin in a webpack build.
I'm using css loader in module mode and postcss loader : 
```
ExtractTextPlugin.extract('style', 'css?modules!postcss')
```
Could it be the fact that the postcss plugins run multiple times on each css module files? The styleguide would have already been created while parsing the first css module file and fail on second generation.

Would there be a way to prevent that?

Thanks!

**Comment by jarodtaylor** [comment]
@jonathanasquier did you resolve this? I'm running into this issue, now too.

**Comment by jonathanasquier** [comment]
Nope, I believe I flew away...

**Comment by jarodtaylor** [comment]
@jonathanasquier yeah, unfortunately, I don't think they're really maintaining this repo much, anymore.
