### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by paazmaya** [jonathantneal/mdcss#6]
Please use `git tag` for tagging the existing and future releases so it will be easier to see what has changed since the previous and/or between two releases.

It will also make it easier to see if a certain fix has been released to `npm` in the given release.

**Comment by jonathantneal** [comment]
Good suggestion. I will keep this open until the next release when I (hopefully) do this successfully. Thank you.

**Comment by jonathantneal** [comment]
Thank you again for this suggestion.

https://github.com/jonathantneal/mdcss/tree/v1.4.1
