### ISSUE TITLE
shorthand hex colors do not work as expected

### ISSUE THREAD

**Issue by maoberlehner** [jonathantneal/mdcss#7]
There is no border around the color and the font color of the color code should be dark

![Shorthand hex color](http://i.imgur.com/CTF4YqB.png)

**Comment by jonathantneal** [comment]
I have replicated this and a fix will arrive in the next release. Thank you! I’ll leave this open until it is published.

**Comment by jonathantneal** [comment]
Great find. This is now fixed in mdcss-theme-github [v2.2.0](https://github.com/jonathantneal/mdcss-theme-github/commit/9d92dab27343967f253d3f924260a573c13706a2)

**Comment by maoberlehner** [comment]
Awesome! This tool makes my life a lot easier, thank you!
